add plasma colormap
pgf-tikz/pgfplots pull request #399
Opened 2021-07-01 08:27 UTC by seeralans

Added the plasma colourmap, one of the perceptually uniform colourmaps orginally designed for matplotlib found here:
https://bids.github.io/colormap/

2021-07-01 10:14 UTC, ilayn approved these changes

2021-07-01 10:38 UTC, hmenke requested changes

2021-07-01 10:38 UTC, hmenke commented on tex/generic/pgfplots/libs/tikzlibrarypgfplots.colormaps.code.tex
> +      rgb=(0.050383, 0.029803, 0.527975)
Please fix the indentation to match the rest of the file.
```suggestion
		  rgb=(0.050383, 0.029803, 0.527975)
```

2021-09-08 10:19 UTC, seeralans commented on tex/generic/pgfplots/libs/tikzlibrarypgfplots.colormaps.code.tex
> +      rgb=(0.050383, 0.029803, 0.527975)
I've fixed this in a commit.

2021-12-29 10:42 UTC, cfeuersaenger approved these changes

2021-12-29 10:43 UTC, merged